// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockTranslationService is an autogenerated mock type for the TranslationService type
type MockTranslationService struct {
	mock.Mock
}

type MockTranslationService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTranslationService) EXPECT() *MockTranslationService_Expecter {
	return &MockTranslationService_Expecter{mock: &_m.Mock}
}

// GetAllForDomain provides a mock function with given fields: domain
func (_m *MockTranslationService) GetAllForDomain(domain string) map[string]string {
	ret := _m.Called(domain)

	if len(ret) == 0 {
		panic("no return value specified for GetAllForDomain")
	}

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func(string) map[string]string); ok {
		r0 = rf(domain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	return r0
}

// MockTranslationService_GetAllForDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllForDomain'
type MockTranslationService_GetAllForDomain_Call struct {
	*mock.Call
}

// GetAllForDomain is a helper method to define mock.On call
//   - domain string
func (_e *MockTranslationService_Expecter) GetAllForDomain(domain interface{}) *MockTranslationService_GetAllForDomain_Call {
	return &MockTranslationService_GetAllForDomain_Call{Call: _e.mock.On("GetAllForDomain", domain)}
}

func (_c *MockTranslationService_GetAllForDomain_Call) Run(run func(domain string)) *MockTranslationService_GetAllForDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTranslationService_GetAllForDomain_Call) Return(_a0 map[string]string) *MockTranslationService_GetAllForDomain_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTranslationService_GetAllForDomain_Call) RunAndReturn(run func(string) map[string]string) *MockTranslationService_GetAllForDomain_Call {
	_c.Call.Return(run)
	return _c
}

// Translate provides a mock function with given fields: domain, key
func (_m *MockTranslationService) Translate(domain string, key string) string {
	ret := _m.Called(domain, key)

	if len(ret) == 0 {
		panic("no return value specified for Translate")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(domain, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockTranslationService_Translate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Translate'
type MockTranslationService_Translate_Call struct {
	*mock.Call
}

// Translate is a helper method to define mock.On call
//   - domain string
//   - key string
func (_e *MockTranslationService_Expecter) Translate(domain interface{}, key interface{}) *MockTranslationService_Translate_Call {
	return &MockTranslationService_Translate_Call{Call: _e.mock.On("Translate", domain, key)}
}

func (_c *MockTranslationService_Translate_Call) Run(run func(domain string, key string)) *MockTranslationService_Translate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockTranslationService_Translate_Call) Return(_a0 string) *MockTranslationService_Translate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTranslationService_Translate_Call) RunAndReturn(run func(string, string) string) *MockTranslationService_Translate_Call {
	_c.Call.Return(run)
	return _c
}

// TranslateWithData provides a mock function with given fields: domain, key, data
func (_m *MockTranslationService) TranslateWithData(domain string, key string, data map[string]string) string {
	ret := _m.Called(domain, key, data)

	if len(ret) == 0 {
		panic("no return value specified for TranslateWithData")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string, map[string]string) string); ok {
		r0 = rf(domain, key, data)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockTranslationService_TranslateWithData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TranslateWithData'
type MockTranslationService_TranslateWithData_Call struct {
	*mock.Call
}

// TranslateWithData is a helper method to define mock.On call
//   - domain string
//   - key string
//   - data map[string]string
func (_e *MockTranslationService_Expecter) TranslateWithData(domain interface{}, key interface{}, data interface{}) *MockTranslationService_TranslateWithData_Call {
	return &MockTranslationService_TranslateWithData_Call{Call: _e.mock.On("TranslateWithData", domain, key, data)}
}

func (_c *MockTranslationService_TranslateWithData_Call) Run(run func(domain string, key string, data map[string]string)) *MockTranslationService_TranslateWithData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(map[string]string))
	})
	return _c
}

func (_c *MockTranslationService_TranslateWithData_Call) Return(_a0 string) *MockTranslationService_TranslateWithData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTranslationService_TranslateWithData_Call) RunAndReturn(run func(string, string, map[string]string) string) *MockTranslationService_TranslateWithData_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTranslationService creates a new instance of MockTranslationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTranslationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTranslationService {
	mock := &MockTranslationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
