// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	ut "github.com/go-playground/universal-translator"

	validator "github.com/go-playground/validator/v10"
)

// MockValidator is an autogenerated mock type for the Validator type
type MockValidator struct {
	mock.Mock
}

type MockValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValidator) EXPECT() *MockValidator_Expecter {
	return &MockValidator_Expecter{mock: &_m.Mock}
}

// Engine provides a mock function with no fields
func (_m *MockValidator) Engine() *validator.Validate {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Engine")
	}

	var r0 *validator.Validate
	if rf, ok := ret.Get(0).(func() *validator.Validate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*validator.Validate)
		}
	}

	return r0
}

// MockValidator_Engine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Engine'
type MockValidator_Engine_Call struct {
	*mock.Call
}

// Engine is a helper method to define mock.On call
func (_e *MockValidator_Expecter) Engine() *MockValidator_Engine_Call {
	return &MockValidator_Engine_Call{Call: _e.mock.On("Engine")}
}

func (_c *MockValidator_Engine_Call) Run(run func()) *MockValidator_Engine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockValidator_Engine_Call) Return(_a0 *validator.Validate) *MockValidator_Engine_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockValidator_Engine_Call) RunAndReturn(run func() *validator.Validate) *MockValidator_Engine_Call {
	_c.Call.Return(run)
	return _c
}

// Struct provides a mock function with given fields: s
func (_m *MockValidator) Struct(s interface{}) error {
	ret := _m.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Struct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockValidator_Struct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Struct'
type MockValidator_Struct_Call struct {
	*mock.Call
}

// Struct is a helper method to define mock.On call
//   - s interface{}
func (_e *MockValidator_Expecter) Struct(s interface{}) *MockValidator_Struct_Call {
	return &MockValidator_Struct_Call{Call: _e.mock.On("Struct", s)}
}

func (_c *MockValidator_Struct_Call) Run(run func(s interface{})) *MockValidator_Struct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockValidator_Struct_Call) Return(_a0 error) *MockValidator_Struct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockValidator_Struct_Call) RunAndReturn(run func(interface{}) error) *MockValidator_Struct_Call {
	_c.Call.Return(run)
	return _c
}

// Translator provides a mock function with no fields
func (_m *MockValidator) Translator() ut.Translator {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Translator")
	}

	var r0 ut.Translator
	if rf, ok := ret.Get(0).(func() ut.Translator); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ut.Translator)
		}
	}

	return r0
}

// MockValidator_Translator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Translator'
type MockValidator_Translator_Call struct {
	*mock.Call
}

// Translator is a helper method to define mock.On call
func (_e *MockValidator_Expecter) Translator() *MockValidator_Translator_Call {
	return &MockValidator_Translator_Call{Call: _e.mock.On("Translator")}
}

func (_c *MockValidator_Translator_Call) Run(run func()) *MockValidator_Translator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockValidator_Translator_Call) Return(_a0 ut.Translator) *MockValidator_Translator_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockValidator_Translator_Call) RunAndReturn(run func() ut.Translator) *MockValidator_Translator_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function with given fields: s
func (_m *MockValidator) Validate(s interface{}) error {
	ret := _m.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - s interface{}
func (_e *MockValidator_Expecter) Validate(s interface{}) *MockValidator_Validate_Call {
	return &MockValidator_Validate_Call{Call: _e.mock.On("Validate", s)}
}

func (_c *MockValidator_Validate_Call) Run(run func(s interface{})) *MockValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockValidator_Validate_Call) Return(_a0 error) *MockValidator_Validate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockValidator_Validate_Call) RunAndReturn(run func(interface{}) error) *MockValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateVar provides a mock function with given fields: field, tag
func (_m *MockValidator) ValidateVar(field interface{}, tag string) error {
	ret := _m.Called(field, tag)

	if len(ret) == 0 {
		panic("no return value specified for ValidateVar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, string) error); ok {
		r0 = rf(field, tag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockValidator_ValidateVar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateVar'
type MockValidator_ValidateVar_Call struct {
	*mock.Call
}

// ValidateVar is a helper method to define mock.On call
//   - field interface{}
//   - tag string
func (_e *MockValidator_Expecter) ValidateVar(field interface{}, tag interface{}) *MockValidator_ValidateVar_Call {
	return &MockValidator_ValidateVar_Call{Call: _e.mock.On("ValidateVar", field, tag)}
}

func (_c *MockValidator_ValidateVar_Call) Run(run func(field interface{}, tag string)) *MockValidator_ValidateVar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(string))
	})
	return _c
}

func (_c *MockValidator_ValidateVar_Call) Return(_a0 error) *MockValidator_ValidateVar_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockValidator_ValidateVar_Call) RunAndReturn(run func(interface{}, string) error) *MockValidator_ValidateVar_Call {
	_c.Call.Return(run)
	return _c
}

// Var provides a mock function with given fields: field, tag
func (_m *MockValidator) Var(field interface{}, tag string) error {
	ret := _m.Called(field, tag)

	if len(ret) == 0 {
		panic("no return value specified for Var")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, string) error); ok {
		r0 = rf(field, tag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockValidator_Var_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Var'
type MockValidator_Var_Call struct {
	*mock.Call
}

// Var is a helper method to define mock.On call
//   - field interface{}
//   - tag string
func (_e *MockValidator_Expecter) Var(field interface{}, tag interface{}) *MockValidator_Var_Call {
	return &MockValidator_Var_Call{Call: _e.mock.On("Var", field, tag)}
}

func (_c *MockValidator_Var_Call) Run(run func(field interface{}, tag string)) *MockValidator_Var_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(string))
	})
	return _c
}

func (_c *MockValidator_Var_Call) Return(_a0 error) *MockValidator_Var_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockValidator_Var_Call) RunAndReturn(run func(interface{}, string) error) *MockValidator_Var_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockValidator creates a new instance of MockValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValidator {
	mock := &MockValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
