// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	chi "github.com/cristiano-pacheco/bricks/pkg/http/server/chi"
	mock "github.com/stretchr/testify/mock"
)

// MockRoute is an autogenerated mock type for the Route type
type MockRoute struct {
	mock.Mock
}

type MockRoute_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoute) EXPECT() *MockRoute_Expecter {
	return &MockRoute_Expecter{mock: &_m.Mock}
}

// Setup provides a mock function with given fields: server
func (_m *MockRoute) Setup(server *chi.Server) {
	_m.Called(server)
}

// MockRoute_Setup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Setup'
type MockRoute_Setup_Call struct {
	*mock.Call
}

// Setup is a helper method to define mock.On call
//   - server *chi.Server
func (_e *MockRoute_Expecter) Setup(server interface{}) *MockRoute_Setup_Call {
	return &MockRoute_Setup_Call{Call: _e.mock.On("Setup", server)}
}

func (_c *MockRoute_Setup_Call) Run(run func(server *chi.Server)) *MockRoute_Setup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*chi.Server))
	})
	return _c
}

func (_c *MockRoute_Setup_Call) Return() *MockRoute_Setup_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRoute_Setup_Call) RunAndReturn(run func(*chi.Server)) *MockRoute_Setup_Call {
	_c.Run(run)
	return _c
}

// NewMockRoute creates a new instance of MockRoute. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoute(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoute {
	mock := &MockRoute{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
