// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockUseCaseMetrics is an autogenerated mock type for the UseCaseMetrics type
type MockUseCaseMetrics struct {
	mock.Mock
}

type MockUseCaseMetrics_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUseCaseMetrics) EXPECT() *MockUseCaseMetrics_Expecter {
	return &MockUseCaseMetrics_Expecter{mock: &_m.Mock}
}

// IncError provides a mock function with given fields: name
func (_m *MockUseCaseMetrics) IncError(name string) {
	_m.Called(name)
}

// MockUseCaseMetrics_IncError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncError'
type MockUseCaseMetrics_IncError_Call struct {
	*mock.Call
}

// IncError is a helper method to define mock.On call
//   - name string
func (_e *MockUseCaseMetrics_Expecter) IncError(name interface{}) *MockUseCaseMetrics_IncError_Call {
	return &MockUseCaseMetrics_IncError_Call{Call: _e.mock.On("IncError", name)}
}

func (_c *MockUseCaseMetrics_IncError_Call) Run(run func(name string)) *MockUseCaseMetrics_IncError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockUseCaseMetrics_IncError_Call) Return() *MockUseCaseMetrics_IncError_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUseCaseMetrics_IncError_Call) RunAndReturn(run func(string)) *MockUseCaseMetrics_IncError_Call {
	_c.Run(run)
	return _c
}

// IncSuccess provides a mock function with given fields: name
func (_m *MockUseCaseMetrics) IncSuccess(name string) {
	_m.Called(name)
}

// MockUseCaseMetrics_IncSuccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncSuccess'
type MockUseCaseMetrics_IncSuccess_Call struct {
	*mock.Call
}

// IncSuccess is a helper method to define mock.On call
//   - name string
func (_e *MockUseCaseMetrics_Expecter) IncSuccess(name interface{}) *MockUseCaseMetrics_IncSuccess_Call {
	return &MockUseCaseMetrics_IncSuccess_Call{Call: _e.mock.On("IncSuccess", name)}
}

func (_c *MockUseCaseMetrics_IncSuccess_Call) Run(run func(name string)) *MockUseCaseMetrics_IncSuccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockUseCaseMetrics_IncSuccess_Call) Return() *MockUseCaseMetrics_IncSuccess_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUseCaseMetrics_IncSuccess_Call) RunAndReturn(run func(string)) *MockUseCaseMetrics_IncSuccess_Call {
	_c.Run(run)
	return _c
}

// ObserveDuration provides a mock function with given fields: name, duration
func (_m *MockUseCaseMetrics) ObserveDuration(name string, duration time.Duration) {
	_m.Called(name, duration)
}

// MockUseCaseMetrics_ObserveDuration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ObserveDuration'
type MockUseCaseMetrics_ObserveDuration_Call struct {
	*mock.Call
}

// ObserveDuration is a helper method to define mock.On call
//   - name string
//   - duration time.Duration
func (_e *MockUseCaseMetrics_Expecter) ObserveDuration(name interface{}, duration interface{}) *MockUseCaseMetrics_ObserveDuration_Call {
	return &MockUseCaseMetrics_ObserveDuration_Call{Call: _e.mock.On("ObserveDuration", name, duration)}
}

func (_c *MockUseCaseMetrics_ObserveDuration_Call) Run(run func(name string, duration time.Duration)) *MockUseCaseMetrics_ObserveDuration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(time.Duration))
	})
	return _c
}

func (_c *MockUseCaseMetrics_ObserveDuration_Call) Return() *MockUseCaseMetrics_ObserveDuration_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUseCaseMetrics_ObserveDuration_Call) RunAndReturn(run func(string, time.Duration)) *MockUseCaseMetrics_ObserveDuration_Call {
	_c.Run(run)
	return _c
}

// NewMockUseCaseMetrics creates a new instance of MockUseCaseMetrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUseCaseMetrics(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUseCaseMetrics {
	mock := &MockUseCaseMetrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
