// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUseCase is an autogenerated mock type for the UseCase type
type MockUseCase[T interface{}, R interface{}] struct {
	mock.Mock
}

type MockUseCase_Expecter[T interface{}, R interface{}] struct {
	mock *mock.Mock
}

func (_m *MockUseCase[T, R]) EXPECT() *MockUseCase_Expecter[T, R] {
	return &MockUseCase_Expecter[T, R]{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, input
func (_m *MockUseCase[T, R]) Execute(ctx context.Context, input T) (R, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 R
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, T) (R, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, T) R); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(R)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, T) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockUseCase_Execute_Call[T interface{}, R interface{}] struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input T
func (_e *MockUseCase_Expecter[T, R]) Execute(ctx interface{}, input interface{}) *MockUseCase_Execute_Call[T, R] {
	return &MockUseCase_Execute_Call[T, R]{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *MockUseCase_Execute_Call[T, R]) Run(run func(ctx context.Context, input T)) *MockUseCase_Execute_Call[T, R] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(T))
	})
	return _c
}

func (_c *MockUseCase_Execute_Call[T, R]) Return(_a0 R, _a1 error) *MockUseCase_Execute_Call[T, R] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_Execute_Call[T, R]) RunAndReturn(run func(context.Context, T) (R, error)) *MockUseCase_Execute_Call[T, R] {
	_c.Call.Return(run)
	return _c
}

// NewMockUseCase creates a new instance of MockUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUseCase[T interface{}, R interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUseCase[T, R] {
	mock := &MockUseCase[T, R]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
