// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockLocaleLoaderService is an autogenerated mock type for the LocaleLoaderService type
type MockLocaleLoaderService struct {
	mock.Mock
}

type MockLocaleLoaderService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLocaleLoaderService) EXPECT() *MockLocaleLoaderService_Expecter {
	return &MockLocaleLoaderService_Expecter{mock: &_m.Mock}
}

// Load provides a mock function with given fields: locale
func (_m *MockLocaleLoaderService) Load(locale string) (map[string]map[string]string, error) {
	ret := _m.Called(locale)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 map[string]map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (map[string]map[string]string, error)); ok {
		return rf(locale)
	}
	if rf, ok := ret.Get(0).(func(string) map[string]map[string]string); ok {
		r0 = rf(locale)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(locale)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLocaleLoaderService_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockLocaleLoaderService_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - locale string
func (_e *MockLocaleLoaderService_Expecter) Load(locale interface{}) *MockLocaleLoaderService_Load_Call {
	return &MockLocaleLoaderService_Load_Call{Call: _e.mock.On("Load", locale)}
}

func (_c *MockLocaleLoaderService_Load_Call) Run(run func(locale string)) *MockLocaleLoaderService_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockLocaleLoaderService_Load_Call) Return(_a0 map[string]map[string]string, _a1 error) *MockLocaleLoaderService_Load_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLocaleLoaderService_Load_Call) RunAndReturn(run func(string) (map[string]map[string]string, error)) *MockLocaleLoaderService_Load_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLocaleLoaderService creates a new instance of MockLocaleLoaderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLocaleLoaderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLocaleLoaderService {
	mock := &MockLocaleLoaderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
