// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockErrorHandler is an autogenerated mock type for the ErrorHandler type
type MockErrorHandler struct {
	mock.Mock
}

type MockErrorHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockErrorHandler) EXPECT() *MockErrorHandler_Expecter {
	return &MockErrorHandler_Expecter{mock: &_m.Mock}
}

// Error provides a mock function with given fields: w, err
func (_m *MockErrorHandler) Error(w http.ResponseWriter, err error) {
	_m.Called(w, err)
}

// MockErrorHandler_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockErrorHandler_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - err error
func (_e *MockErrorHandler_Expecter) Error(w interface{}, err interface{}) *MockErrorHandler_Error_Call {
	return &MockErrorHandler_Error_Call{Call: _e.mock.On("Error", w, err)}
}

func (_c *MockErrorHandler_Error_Call) Run(run func(w http.ResponseWriter, err error)) *MockErrorHandler_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(error))
	})
	return _c
}

func (_c *MockErrorHandler_Error_Call) Return() *MockErrorHandler_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockErrorHandler_Error_Call) RunAndReturn(run func(http.ResponseWriter, error)) *MockErrorHandler_Error_Call {
	_c.Run(run)
	return _c
}

// NewMockErrorHandler creates a new instance of MockErrorHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockErrorHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockErrorHandler {
	mock := &MockErrorHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
