// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockErrorTranslator is an autogenerated mock type for the ErrorTranslator type
type MockErrorTranslator struct {
	mock.Mock
}

type MockErrorTranslator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockErrorTranslator) EXPECT() *MockErrorTranslator_Expecter {
	return &MockErrorTranslator_Expecter{mock: &_m.Mock}
}

// TranslateError provides a mock function with given fields: err
func (_m *MockErrorTranslator) TranslateError(err error) error {
	ret := _m.Called(err)

	if len(ret) == 0 {
		panic("no return value specified for TranslateError")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(error) error); ok {
		r0 = rf(err)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockErrorTranslator_TranslateError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TranslateError'
type MockErrorTranslator_TranslateError_Call struct {
	*mock.Call
}

// TranslateError is a helper method to define mock.On call
//   - err error
func (_e *MockErrorTranslator_Expecter) TranslateError(err interface{}) *MockErrorTranslator_TranslateError_Call {
	return &MockErrorTranslator_TranslateError_Call{Call: _e.mock.On("TranslateError", err)}
}

func (_c *MockErrorTranslator_TranslateError_Call) Run(run func(err error)) *MockErrorTranslator_TranslateError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(error))
	})
	return _c
}

func (_c *MockErrorTranslator_TranslateError_Call) Return(_a0 error) *MockErrorTranslator_TranslateError_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockErrorTranslator_TranslateError_Call) RunAndReturn(run func(error) error) *MockErrorTranslator_TranslateError_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockErrorTranslator creates a new instance of MockErrorTranslator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockErrorTranslator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockErrorTranslator {
	mock := &MockErrorTranslator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
